// apps/app-history-spa/src/components/LambdaInfo.tsx
import { FC, ReactNode } from "react";
import lambdaSvg from "../assets/lambda.svg";
import styles from "./LambdaInfo.module.scss";

type LambdaInfoProps = {
  name: string;
  children: ReactNode;
};

export const LambdaInfo: FC<LambdaInfoProps> = ({ name, children }) => (
  <div className={styles.wrapper}>
    <h2>
      <img src={lambdaSvg} alt="lambda icon" /> {name}
    </h2>
    <hr />

    {children}
  </div>
);

// apps/app-edge/src/lib/LambdaInfo.svelte
<script lang="ts">
  import lambdaSvg from "./assets/lambda.svg";

  export let name: string;
</script>

<div>
  <h2><img src={lambdaSvg} alt="lambda icon" class="lambda" /> {name}</h2>
  <hr />

  <slot />
</div>

<style lang="scss">
  .lambda {
    height: 0.7em;
  }

  h2 {
    font-size: 2.5rem;
  }

  hr {
    height: 2px;
    color: currentColor;
    border-radius: 2px;
    width: 70px;
    margin: 10px auto 30px;
  }
</style>
